global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'devportfolio'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:5000']

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: devportfolio-prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    jsonData:
      httpMethod: POST