{
 "title": "DevPortfolio - Monitoring",
 "description": "DevPortfolio - Métriques Flask / Prometheus",
 "tags": [
  "devportfolio",
  "flask",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requêtes HTTP par seconde",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, status) (rate(flask_http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Latence moyenne (s)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[1m]) / rate(flask_http_request_duration_seconds_count[1m])",
     "legendFormat": "Latence moy."
    }
   ]
  },
  {
   "title": "Exceptions Flask",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_exceptions_total",
     "legendFormat": "Exceptions"
    }
   ]
  }
 ]
}