name: CI/CD Pipeline Complet

on:
  push:
    branches: [main]

jobs:

  build-and-push:
    name: Build et Push Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Se connecter a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construire et pousser l'image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mon-app:latest

  notification:
    name: Notification de succes
    runs-on: ubuntu-latest
    needs: [tests, build-and-push]
    if: success()
    steps:
      - run: echo 'Pipeline termine avec succes !'
